# Generated by Django 2.0.2 on 2018-03-14 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import evaluator.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, max_length=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('html', evaluator.fields.HTMLField(default='')),
                ('url', models.URLField(default='')),
                ('status', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evaluator.Applicant')),
            ],
        ),
    ]
