# Generated by Django 2.0.2 on 2018-03-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='data',
        ),
        migrations.AddField(
            model_name='applicant',
            name='username_proxy',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
